import React from "react";

const PrivacyPolicy = () => {
  return (
    <div className="p-8 bg-[#181818] text-slate-300 min-h-screen">
      <h1 className="text-3xl font-bold mb-4 text-slate-100">Privacy Policy for Get QR Code Now</h1>
      <p className="mb-4">
      <p>Last updated: November 06, 2024</p>
<p>
  This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and informs You about Your privacy rights and how the law protects You.
</p>
<p>
  We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
</p>

<p><strong>Interpretation and Definitions</strong></p>

<p><strong>Interpretation</strong></p>
<p>
  Words with the initial letter capitalized have specific meanings defined below. These definitions have the same meaning regardless of whether they appear in singular or plural form.
</p>

<p><strong>Definitions</strong></p>
<p>For the purposes of this Privacy Policy:</p>
<ul>
  <li>Account: A unique account created for You to access our Service or parts of our Service.</li>
  <li>Company (referred to as "the Company," "We," "Us," or "Our" in this Agreement): Refers to Get QR Code Now.</li>
  <li>Cookies: Small files placed on Your Device by a website, containing details of Your browsing history and other uses.</li>
  <li>Country: Refers to Costa Rica.</li>
  <li>Device: Any device that can access the Service, such as a computer, cellphone, or digital tablet.</li>
  <li>Personal Data: Any information that relates to an identified or identifiable individual.</li>
  <li>Service: Refers to the Website.</li>
  <li>Service Provider: Any natural or legal person who processes data on behalf of the Company.</li>
  <li>Usage Data: Data collected automatically, either generated by using the Service or from the Service infrastructure itself.</li>
  <li>Website: Get QR Code Now, accessible from <a href="https://getqrcodenow.com">https://getqrcodenow.com</a></li>
  <li>You: The individual accessing or using the Service, or the company or legal entity on behalf of which such individual is accessing or using the Service.</li>
</ul>

<p><strong>Collecting and Using Your Personal Data</strong></p>

<p><strong>Types of Data Collected</strong></p>

<p><strong>Personal Data</strong></p>
<p>
  While using Our Service, We may ask You to provide certain personally identifiable information, including but not limited to:
</p>
<ul>
  <li>Email address</li>
  <li>First name and last name</li>
  <li>Usage Data</li>
</ul>

<p><strong>Usage Data</strong></p>
<p>
  Usage Data is collected automatically when using the Service. This may include information such as Your Device's IP address, browser type, browser version, pages of our Service visited, time and date of Your visit, time spent on those pages, and other diagnostic data.
</p>

<p><strong>Tracking Technologies and Cookies</strong></p>
<p>
  We use Cookies and similar tracking technologies to track activity on Our Service and store certain information. Technologies used may include:
</p>
<ul>
  <li>Cookies or Browser Cookies</li>
  <li>Web Beacons</li>
</ul>
<p>
  Cookies can be "Persistent" or "Session" Cookies. For more details, see our Cookies Policy.
</p>

<p><strong>Use of Your Personal Data</strong></p>
<p>The Company may use Personal Data for the following purposes:</p>
<ul>
  <li>To provide and maintain our Service.</li>
  <li>To manage Your Account.</li>
  <li>For contract performance.</li>
  <li>To contact You.</li>
  <li>To manage Your requests.</li>
  <li>For business transfers.</li>
  <li>For data analysis and service improvement.</li>
</ul>

<p><strong>Retention of Your Personal Data</strong></p>
<p>
  The Company will retain Your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy.
</p>

<p><strong>Transfer of Your Personal Data</strong></p>
<p>
  Your information may be transferred to — and maintained on — computers located outside of Your jurisdiction where the data protection laws may differ.
</p>

<p><strong>Delete Your Personal Data</strong></p>
<p>
  You have the right to delete or request the deletion of Your Personal Data. You may contact Us for assistance.
</p>

<p><strong>Disclosure of Your Personal Data</strong></p>
<ul>
  <li>Business Transactions: If the Company is involved in a merger or sale, Personal Data may be transferred.</li>
  <li>Law enforcement: Under certain circumstances, disclosure may be required by law.</li>
  <li>Other legal requirements: The Company may disclose Your Personal Data to comply with legal obligations.</li>
</ul>

<p><strong>Security of Your Personal Data</strong></p>
<p>
  We use commercially acceptable means to protect Your Personal Data, but no method of transmission over the Internet or electronic storage is 100% secure.
</p>

<p><strong>GDPR, CCPA, and CPRA Compliance</strong></p>

<p><strong>Your Data Protection Rights Under GDPR</strong></p>
<p>If You are a resident of the European Economic Area (EEA), You have the following data protection rights:</p>
<ul>
  <li>Right to Access: You have the right to request copies of Your Personal Data.</li>
  <li>Right to Rectification: You have the right to request correction of inaccurate or incomplete information.</li>
  <li>Right to Erasure: You have the right to request deletion of Your Personal Data.</li>
  <li>Right to Restrict Processing: You have the right to request the restriction of Your Personal Data processing.</li>
  <li>Right to Data Portability: You have the right to receive Your Personal Data in a structured, machine-readable format.</li>
  <li>Right to Object: You have the right to object to Our processing of Your Personal Data.</li>
  <li>Right to Withdraw Consent: If we rely on consent for processing, You can withdraw consent at any time.</li>
</ul>

<p><strong>Your Data Protection Rights Under CCPA and CPRA</strong></p>
<p>If You are a California resident, You have the following rights:</p>
<ul>
  <li>Right to Know: You have the right to request that We disclose what Personal Data We collect, use, or share.</li>
  <li>Right to Delete: You have the right to request the deletion of Your Personal Data.</li>
  <li>Right to Opt-Out: You have the right to opt-out of the sale or sharing of Your Personal Data.</li>
  <li>Right to Non-Discrimination: You will not be discriminated against for exercising Your rights.</li>
  <li>Right to Correct: You have the right to request correction of inaccurate Personal Data.</li>
  <li>Right to Limit Use of Sensitive Personal Data: You can restrict the use of sensitive data.</li>
</ul>

<p><strong>Advertising and Google AdSense</strong></p>
<p>
  Our Service may display advertisements provided by Google AdSense. Google AdSense is an advertising service provided by Google that uses Cookies to show ads based on users' previous visits to our Website and other websites on the Internet.
</p>

<p><strong>How Google AdSense Works:</strong></p>
<ul>
  <li>Google may use Cookies and other tracking technologies to collect information about your use of our Website in order to display personalized ads.</li>
  <li>The data collected may include your IP address, device type, browser type, and browsing behavior. This data helps Google and its partners provide relevant ads that match your interests.</li>
  <li>Google AdSense may use DoubleClick Cookie to track usage data and user behavior.</li>
</ul>

<p><strong>Your Choices:</strong></p>
<ul>
  <li>Managing Cookies: You can opt-out of personalized advertising by visiting <a href="https://adssettings.google.com/authenticated">Google Ads Settings</a>. Additionally, you can disable cookies entirely through your browser settings.</li>
  <li>Other Options: You may also opt out of some third-party vendors’ use of cookies for personalized advertising by visiting <a href="https://www.aboutads.info/choices">www.aboutads.info</a>.</li>
</ul>

<p><strong>Third-Party Policies:</strong></p>
<p>
  Our Privacy Policy does not apply to third-party advertisers or websites. For detailed information about how Google collects and processes data, please visit <a href="https://policies.google.com/technologies/ads">Google's Privacy Policy</a>.
</p>

<p><strong>Use of Advertising Partners:</strong></p>
<p>
  We may partner with other third-party advertisers that also use cookies and web beacons on our Website to display ads and track user activity. These third parties may have their own Privacy Policies, which we recommend reviewing.
</p>

<p><strong>Data Collection by Google AdSense:</strong></p>
<p>
  By using our Website, you consent to the processing of data about you by Google in the manner and for the purposes set out above. If you do not wish for your data to be collected and used by Google AdSense, you should adjust your browser settings to disable cookies.
</p>

<p><strong>Exercising Your Rights</strong></p>
<p>
  To exercise any of Your rights under GDPR, CCPA, or CPRA, please contact Us at <a href="mailto:tusolucionenlanube@gmail.com">tusolucionenlanube@gmail.com</a>.
</p>

<p><strong>Children's Privacy</strong></p>
<p>
  Our Service does not address anyone under the age of 13. If We discover that Personal Data from children under 13 has been collected without parental consent, We will take steps to remove such data.
</p>

<p><strong>Links to Other Websites</strong></p>
<p>
  Our Service may contain links to other websites. We have no control over and assume no responsibility for their content or policies.
</p>

<p><strong>Changes to this Privacy Policy</strong></p>
<p>
  We may update this Privacy Policy from time to time. Any changes will be posted on this page with an updated "Last updated" date.
</p>

<p><strong>Contact Us</strong></p>
<p>
  If you have questions about this Privacy Policy, please contact us:
</p>
<ul>
  <li>By email: <a href="mailto:tusolucionenlanube@gmail.com">tusolucionenlanube@gmail.com</a></li>
</ul>
      
      </p>
      <p>
        Ensure you include information on cookies, data retention, third-party services, and user rights.
      </p>
    </div>
  );
};

export default PrivacyPolicy;
